### ISSUE TITLE
Unnecessary abstraction layer in .y file

### ISSUE THREAD

**Issue by irek14** [szymon159/mini-compiler#7]
https://github.com/szymon159/mini-compiler/blob/ac759cf13b0c92520e6ae9f871fb13308904778f/MiniCompiler/MiniCompiler/kompilator.y#L42

In the statement presented above (and many other places) you use `Compiler.GetLineNumber()`. Why do not simply use `yyline`?

**Comment by szymon159** [comment]
Hello, sorry for the late reply 😅 I've investigated the issue and seems you are right. As far as I remember, this method has been used in order to store the line number inside of `Compiler` class, debug, and adjust line number when reporting exceptions. But in current version, it is no longer necessary.

Nevertheless, I don't find this approach problematic nor negatively impacting any results. For this reason, no update is planned and the issue will be closed.
